@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> MainWindow

state MainWindow {
  [*] --> ItemWindow: Choice
}

state ItemWindow {
[*] --> Time
[*] --> Takeon
[*] --> Takeoff
}
@enduml