@startuml
'https://plantuml.com/activity-diagram-beta

start
:  Администратор открывает
раздел добавления полетов;
:Администратор нажимает
      на кнопку "Add Flight";
repeat
:Заполенение формы с информацией о полете;
repeat while (Проверка на введенные данные) is (false)
 ->true;
:Просмотр заполненой информации;
:Подтверждение добавления полета;
:Информация о полете добавлена;
stop

@enduml
