@startuml
start

:Открытие окна настроек пользователя;
repeat
:Заполение полей;
:Нажатие на кнопку "Save";
repeat while(Проверка введенных данных) is (false)
-> (true);
:Внесение изменений в профиль;

stop

@enduml
